spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/zoostore
    username: postgres
    password: 123
#    url: postgres://qnfkjfkrtbtqsi:eab1f385ba4d7f04866b01d47a1583c79eb12e56fbeaa2402f64c604b19c9b43@ec2-176-34-211-0.eu-west-1.compute.amazonaws.com:5432/dad9j59gagk2p7
#    username: qnfkjfkrtbtqsi
#    password: eab1f385ba4d7f04866b01d47a1583c79eb12e56fbeaa2402f64c604b19c9b43
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 422824741850-v7076qld2jlq73egm0302u3og576v4b1.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
#          facebook:
#            client-id: 1400964657004604
#            client-secret: 278e2e09f0cc06959c7a26905a00aac5
  mail:
    host: smtp.gmail.com
    port: 587
    user: ZooStore
    username: testaccserikzhan@gmail.com
    password: Zoostore2022
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

custom-properties:
#  domain: https://zoo-store.herokuapp.com/
  domain: http://localhost:8080

security:
  token:
    prefix: Bearer
    client-ip: ZooStoreClientIp
    secret: Ijn!nyw#@e7201cVw32102#5@9lh6TgR7Mb!@#cCEidbeiYUdew
    issuer: ZooStoreIssuer server
    audience: ZooStore client
    expiration-time: 3600000
    jwt-token-header: token
    token-cannot-be-verified: token cannot be verified